# Generated by Django 5.1 on 2024-09-16 03:43

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='IndicePrice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('symbol', models.CharField(max_length=10)),
                ('name', models.CharField(default='Unknown', max_length=30)),
                ('current_price', models.FloatField()),
                ('day_low', models.FloatField()),
                ('day_high', models.FloatField()),
                ('previous_close', models.FloatField()),
            ],
        ),
    ]
