# Generated by Django 5.0.7 on 2024-07-25 07:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('indices', '0002_rename_stockprice_indiceprice'),
    ]

    operations = [
        migrations.AddField(
            model_name='indiceprice',
            name='name',
            field=models.CharField(default='Unknown', max_length=30),
        ),
    ]
