# Generated by Django 5.1 on 2024-09-14 12:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('indices', '0003_indiceprice_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='indiceprice',
            name='day_range',
        ),
        migrations.RemoveField(
            model_name='indiceprice',
            name='fifty_two_week_range',
        ),
        migrations.RemoveField(
            model_name='indiceprice',
            name='last_updated',
        ),
        migrations.RemoveField(
            model_name='indiceprice',
            name='open',
        ),
        migrations.RemoveField(
            model_name='indiceprice',
            name='volume',
        ),
    ]
