# Generated by Django 5.0.7 on 2024-07-20 04:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stockprice', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='IndicesPrice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('symbol', models.CharField(max_length=10)),
                ('current_price', models.FloatField(blank=True, null=True)),
                ('day_low', models.FloatField(blank=True, null=True)),
                ('day_high', models.FloatField(blank=True, null=True)),
                ('previous_close', models.FloatField(blank=True, null=True)),
                ('open', models.FloatField(blank=True, null=True)),
                ('fifty_two_week_range', models.CharField(blank=True, max_length=50, null=True)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='stockprice',
            name='eps',
        ),
        migrations.RemoveField(
            model_name='stockprice',
            name='pe_ratio',
        ),
    ]
